name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 3: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Start the React app
      - name: Start Vite App
        run: npm run dev
        
      #  env:
      #    CI: true

      # Step 6: Wait for the app to be ready
      - name: Wait for Vite App
        #wait-on: 'http://localhost:5173'
        run: npx wait-on http://127.0.0.1:5173

      # Step 7: Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run

      # Step 8: Upload Failure Screenshots
      - name: Upload Failure Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: ./cypress/screenshots
